---
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: drpsrv
        memory: '768'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port: {  }
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            varwww:
                owner: ''
                group: ''
                source: ./
                target: /var/www
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: hw
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - htop
        - git
        - unzip
        - php5-memcache
        - vim
        - curl
        - zsh
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules:
        mysqlport:
            port:
                - '3306'
            priority: '100'
            proto: tcp
            action: accept
        seleniumport:
            port:
                - '4444'
            priority: '100'
            proto: tcp
            action: accept
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        drupaldev:
            servername: drupal.dev
            docroot: /var/www/drupal/docroot
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                docroot:
                    provider: directory
                    path: /var/www/drupal/docroot
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: '1'
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        IWmjxjm1NfXC:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - apcu
            - cli
            - curl
            - fpm
            - gd
            - imap
            - intl
            - mbstring
            - mcrypt
            - memcache
            - mysql
            - mysqlnd
            - sqlite
            - sybase
        pear:
            - PHP_CodeSniffer
        pecl:
            - pecl_http
    ini:
        display_errors: On
        display_startup_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        max_execution_time: '300'
        mbstring.http_input: pass
        mbstring.http_output: pass
        mbstring.encoding_translation: '0'
        memory_limit: 384M
        opcache.fast_shutdown: '1'
        opcache.interned_strings_buffer: '8'
        opcache.max_accelerated_files: '4000'
        opcache.memory_consumption: '128'
        opcache.revalidate_freq: '60'
    timezone: Asia/Kolkata
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '1'
wpcli:
    install: '0'
    version: ''
drush:
    install: '1'
    version: 7.0.0-alpha8
ruby:
    install: '1'
    versions:
        OTFYHVjI6Klb:
            version: ''
            bundler: '1'
nodejs:
    install: '1'
    npm_packages:
        - grunt
        - bower
        - gulp
python:
    install: '1'
    packages: {  }
    versions:
        adtG0eUBmhfs:
            version: ''
mysql:
    install: '1'
    override_options: {  }
    root_password: vagrant
    adminer: '1'
    databases:
        drupaldb:
            grant:
                - ALL
            name: drupal
            host: localhost
            user: drupal
            password: vagrant
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '1'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: ''
        java_install: true
solr:
    install: '1'
    settings:
        version: 4.10.2
        port: ''

